/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package employee.payroll.system.LOGINCONNECTION;

/**
 *
 * @author Hyrex
 */

import employee.payroll.system.MainMenu;
import employee.payroll.system.EMPLOYEACCESS.MainMenu1;
import java.awt.*;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.*;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
public class login extends javax.swing.JFrame {
Connection conn=null;
ResultSet rs=null;
PreparedStatement pst=null;

    /**
     * Creates new form Login_jframe
     */

private StringBuilder realPassword = new StringBuilder();

    
   public login() {
    initComponents();

    // class-level variable: 
    // private StringBuilder realPassword = new StringBuilder();

    // attach key listener to txt_password
   txt_password.addKeyListener(new KeyAdapter() {
    @Override
    public void keyTyped(KeyEvent evt) {
        char c = evt.getKeyChar();

        // Ignore control characters (Enter, Ctrl, Shift, CapsLock, etc.)
        if (Character.isISOControl(c)) {
            evt.consume();
            return;
        }

        int selStart = txt_password.getSelectionStart();
        int selEnd = txt_password.getSelectionEnd();
        int selLength = selEnd - selStart;

        // Remove selected range first
        if (selLength > 0) {
            realPassword.delete(selStart, selEnd);
        }

        // Append the new character
        realPassword.insert(selStart, c);

        // Show asterisks
        final int length = realPassword.length();
        SwingUtilities.invokeLater(() -> {
            txt_password.setText("*".repeat(length));
            txt_password.setCaretPosition(selStart + 1);
        });

        evt.consume(); // prevent real character from appearing
    }

    @Override
    public void keyPressed(KeyEvent evt) {
        char c = evt.getKeyChar();
        int selStart = txt_password.getSelectionStart();
        int selEnd = txt_password.getSelectionEnd();
        int selLength = selEnd - selStart;

        // Only handle backspace
        if (evt.getKeyCode() == KeyEvent.VK_BACK_SPACE) {
            if (selLength > 0) {
                realPassword.delete(selStart, selEnd);
            } else if (selStart > 0) {
                realPassword.deleteCharAt(selStart - 1);
            }

            final int length = realPassword.length();
            SwingUtilities.invokeLater(() -> {
                txt_password.setText("*".repeat(length));
                txt_password.setCaretPosition(selStart > 0 ? selStart - 1 : 0);
            });

            evt.consume();
        }
    }
});

    // rest of your constructor code
    conn = db.java_db();
    currentDate();
}
    

    public void currentDate (){
        
        Calendar cal =new GregorianCalendar();
        int month = cal.get(Calendar.MONTH);
        int year = cal.get(Calendar.YEAR);
        int day = cal.get(Calendar.DAY_OF_MONTH);
        
        txt_date.setText((month+1)+"/"+day+"/"+year);
        
        int second = cal.get(Calendar.SECOND);
        int minute = cal.get(Calendar.MINUTE);
        int hour = cal.get(Calendar.HOUR);
        
        lbl_time.setText(hour+":"+(minute)+":"+second);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPanel2 = new javax.swing.JPanel();
        cmd_Login = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_username = new javax.swing.JTextField();
        txt_password = new javax.swing.JTextField();
        txt_combo = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        txt_date = new javax.swing.JMenu();
        lbl_time = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        jMenu1.setText("jMenu1");

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(255, 153, 0));
        jPanel2.setLayout(null);

        cmd_Login.setText("Login");
        cmd_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_LoginActionPerformed(evt);
            }
        });
        cmd_Login.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cmd_LoginKeyPressed(evt);
            }
        });
        jPanel2.add(cmd_Login);
        cmd_Login.setBounds(590, 470, 70, 30);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 0));
        jLabel1.setText("Username:");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(450, 350, 70, 16);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 0));
        jLabel2.setText("Password:");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(450, 390, 70, 16);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 0, 0));
        jLabel6.setText("Please enter your username and password");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(440, 310, 234, 14);

        txt_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_usernameActionPerformed(evt);
            }
        });
        jPanel2.add(txt_username);
        txt_username.setBounds(540, 340, 130, 30);

        txt_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_passwordActionPerformed(evt);
            }
        });
        txt_password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_passwordKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_passwordKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_passwordKeyTyped(evt);
            }
        });
        jPanel2.add(txt_password);
        txt_password.setBounds(540, 380, 130, 30);

        txt_combo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Admin", "Employee", " " }));
        txt_combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_comboActionPerformed(evt);
            }
        });
        jPanel2.add(txt_combo);
        txt_combo.setBounds(540, 420, 130, 30);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 0));
        jLabel3.setText("Select Position:");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(450, 430, 100, 16);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/employee/payroll/system/Images/Motor1.png"))); // NOI18N
        jPanel2.add(jLabel4);
        jLabel4.setBounds(0, 0, 690, 510);

        jMenu2.setText("File");

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/employee/payroll/system/Images/Exit.png"))); // NOI18N
        jMenuItem2.setText("Exit");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);
        jMenuBar1.add(jMenu3);

        txt_date.setText("Date");
        jMenuBar1.add(txt_date);

        lbl_time.setText("Time");
        jMenuBar1.add(lbl_time);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 788, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmd_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_LoginActionPerformed
        // TODO add your handling code here:                                       
        
   if (txt_username.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(null, "Username Field is empty");
        return;
    }
    if (txt_password.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(null, "Password Field is empty");
        return;
    }

    String usernameInput = txt_username.getText().trim();
    String passwordInput = realPassword.toString();
    String selectedDivision = txt_combo.getSelectedItem().toString();

    String query = "SELECT id, username, password, division, failed_attempts, account_locked FROM Users WHERE username = ?";

    try (PreparedStatement pstQuery = conn.prepareStatement(query)) {
        pstQuery.setString(1, usernameInput);

        try (ResultSet rsQuery = pstQuery.executeQuery()) {
            if (!rsQuery.next()) {
                JOptionPane.showMessageDialog(null, "Username not found");
                return;
            }

            int id = rsQuery.getInt("id");
            String dbPassword = rsQuery.getString("password");
            String dbDivision = rsQuery.getString("division");
            int failedAttempts = rsQuery.getInt("failed_attempts");
            int accountLocked = rsQuery.getInt("account_locked");

            // --------------------------
            // BLOCK if account is locked
            // --------------------------
            if (accountLocked == 1) {
                JOptionPane.showMessageDialog(null, "Account is locked. Please contact administrator.");
                insertAudit(id, "Attempted login on locked account");
                return;
            }

            boolean passwordMatches = dbPassword.equals(passwordInput);
            boolean divisionMatches = dbDivision != null && dbDivision.equalsIgnoreCase(selectedDivision);

            // --------------------------
            // WRONG PASSWORD
            // --------------------------
            if (!passwordMatches) {
                failedAttempts++;

                insertAudit(id, "Failed login attempt");

                if (failedAttempts >= 3) {
                    // Lock account
                    String lockSql = "UPDATE Users SET failed_attempts = ?, account_locked = 1 WHERE id = ?";
                    try (PreparedStatement pstLock = conn.prepareStatement(lockSql)) {
                        pstLock.setInt(1, failedAttempts);
                        pstLock.setInt(2, id);
                        pstLock.executeUpdate();
                    }
                    insertAudit(id, "Account locked");
                    JOptionPane.showMessageDialog(null, "Account locked due to 3 failed attempts. Contact administrator.");
                } else {
                    // Update remaining attempts
                    String updateSql = "UPDATE Users SET failed_attempts = ? WHERE id = ?";
                    try (PreparedStatement pstUpdate = conn.prepareStatement(updateSql)) {
                        pstUpdate.setInt(1, failedAttempts);
                        pstUpdate.setInt(2, id);
                        pstUpdate.executeUpdate();
                    }
                    JOptionPane.showMessageDialog(null, "Invalid password. " + failedAttempts + " attempt(s) used of 3.");
                }
                return;
            }

            // --------------------------
            // CORRECT PASSWORD BUT WRONG DIVISION
            // --------------------------
            if (!divisionMatches) {
                JOptionPane.showMessageDialog(null, "Correct password but wrong division selected.");
                insertAudit(id, "Failed login attempt - wrong division");
                return;
            }

            // --------------------------
            // SUCCESS LOGIN
            // --------------------------
            // Reset failed attempts since login is successful
            String resetSql = "UPDATE Users SET failed_attempts = 0 WHERE id = ?";
            try (PreparedStatement pstReset = conn.prepareStatement(resetSql)) {
                pstReset.setInt(1, id);
                pstReset.executeUpdate();
            }

            insertAudit(id, "Logged in");
            Emp.empId = id;

            // --------------------------
            // OPEN MENU BASED ON DIVISION
            // --------------------------
            if ("Admin".equalsIgnoreCase(selectedDivision)) {
                MainMenu adminMenu = new MainMenu();
                adminMenu.setVisible(true);
            } else if ("Employee".equalsIgnoreCase(selectedDivision)) {
                MainMenu1 empMenu = new MainMenu1();
                empMenu.setVisible(true);
            } else {
                MainMenu defaultMenu = new MainMenu();
                defaultMenu.setVisible(true);
            }

            this.dispose(); // close login form
        }
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(null, "Login error: " + ex.getMessage());
        ex.printStackTrace();
    }
}

// =========================
// AUDIT HELPER (unchanged)
private void insertAudit(int empId, String status) {
    String insertAuditSql = "INSERT INTO Audit (emp_id, date, status) VALUES (?, ?, ?)";
    PreparedStatement pstAudit = null;
    try {
        Date now = GregorianCalendar.getInstance().getTime();
        SimpleDateFormat sdfDate = new SimpleDateFormat("yyyy-MM-dd");
        SimpleDateFormat sdfTime = new SimpleDateFormat("HH:mm:ss");
        String dateString = sdfDate.format(now);
        String timeString = sdfTime.format(now);
        String dateTime = timeString + " / " + dateString;

        pstAudit = conn.prepareStatement(insertAuditSql);
        pstAudit.setInt(1, empId);
        pstAudit.setString(2, dateTime);
        pstAudit.setString(3, status);
        pstAudit.executeUpdate();
    } catch (Exception e) {
        System.err.println("Audit insert failed: " + e.getMessage());
        e.printStackTrace();
    } finally {
        try {
            if (pstAudit != null) pstAudit.close();
        } catch (Exception e) {}
    }



    }//GEN-LAST:event_cmd_LoginActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:#
        System.exit(0); 
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void cmd_LoginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmd_LoginKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmd_LoginKeyPressed

    private void txt_comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_comboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_comboActionPerformed

    private void txt_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_usernameActionPerformed

    private void txt_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_passwordActionPerformed

    private void txt_passwordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_passwordKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_passwordKeyPressed

    private void txt_passwordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_passwordKeyTyped
        // TODO add your handling code here

    }//GEN-LAST:event_txt_passwordKeyTyped

    private void txt_passwordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_passwordKeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_txt_passwordKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmd_Login;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JMenu lbl_time;
    private javax.swing.JComboBox txt_combo;
    private javax.swing.JMenu txt_date;
    private javax.swing.JTextField txt_password;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
